= Cron library
:toc: right

== Introduction

NOTE: Versions 2.x target XP 8+.

To start using this library, add the following into your `build.gradle` file:

[source,groovy]
----
dependencies {
  include 'com.enonic.lib:lib-cron:{version}'
}
----

== Usage

To use this library in your JavaScript code, it first needs to be required:

[source,js]
----
var cronLib = require('/lib/cron');
----

=== TypeScript

Type declarations are published as `@enonic-types/lib-cron`, generated from the library source so
the version matches the jar:

[source,bash]
----
npm install --save-dev @enonic-types/lib-cron
----

Add it to both `types` and `paths` in `tsconfig.json` — the `types` entry is what types
`require('/lib/cron')`, the `paths` entry is what resolves `import ... from '/lib/cron'`:

[source,json]
----
{
  "compilerOptions": {
    "types": ["@enonic-types/global", "@enonic-types/lib-cron"],
    "paths": {
      "/lib/cron": ["./node_modules/@enonic-types/lib-cron"]
    }
  }
}
----

=== `Schedule`

Use the following code to schedule a task:

[source,js]
----
var view = cronLib.schedule(params);
----

*Parameters*

The schedule function takes a parameter object with options.

* `options` (_object_) Parameters to schedule a task.
** `*name*` (_string_) Unique task name.
** `*cron*` (_string_) Cron-pattern (see https://en.wikipedia.org/wiki/Cron[UINX cron pattern]). Can't be set with (`*fixedDelay*`/`*delay*`).
** `*fixedDelay*` (_number_) The delay between the termination of one execution and the commencement of the next. Required, and bigger than `0`, when `*cron*` is not set. Can't be set with (`*cron*`).
** `*delay*` (_number_) The time to delay first execution. Can't be set with (`*cron*`).
** `*times*` (_number_) The number of times the task will be executed. Leave it empty for infinite calls.
** `*callback*` (_function_) Code of task which should be called.
** `*context*` (_object_) Context of the task run.
*** `*repository*` (_string_) Repository to execute the callback in.
*** `*branch*` (_string_) Name of the branch to execute the callback in.
*** `*principals*` (_string[]_) Additional principals to execute the callback with.
*** `*attributes*` (_object_) Additional Context attributes.
*** `*user*` (_object_) User credentials.
**** `*login*` (_string_) User login.
**** `*idProvider*` (_string_) Id provider containing the user. Required when `*user*` is set.

=== `Unschedule`

Use `unschedule` method to unschedule a scheduled task:

[source,js]
----
var view = cronLib.unschedule(params);
----

*Parameters*

The unschedule function takes a parameter object with only one option - run task name:

* `options` (_object_) Parameters to unschedule a task.
** `*name*` (_string_) Name of a scheduled task.

=== `Reschedule`
Rescheduling will stop a scheduled task by the name and rerun it using parameters similar to arguments of the `schedule` method:


[source,js]
----
var view = cronLib.reschedule(params);
----

=== `Fetch`

To get an instance of a particular task use `get` method:

[source,js]
----
var task = cronLib.get(params);
----

*Parameters*

The get function takes a parameter object with only one option - task name:

* `options` (_object_) Parameters to get task info.
** `*name*` (_string_) Name of a scheduled task.

And the result is task mapper object, which contains description of run task:

*Result*

* `result` (_object_) task mapper object.
** `*name*` (_string_) Name of a scheduled task.
** `*cron*` (_string_) Cron-pattern (see https://en.wikipedia.org/wiki/Cron[UINX cron pattern]).
** `*cronDescription*` (_string_) Human readable description of UINX cron pattern.
** `*fixedDelay*` (_number_) The delay between the termination of one execution and the commencement of the next.
** `*delay*` (_number_) The time to delay first execution.
** `*applicationKey*` (_string_) Key of application has run the task.
** `*context*` (_object_) Contains information about task context(repo, branch, authInfo).
** `*nextExecTime*` (_string_) Provides nearest time for next execution in ISO 8601 format. Cron tasks only.

To fetch a list of all scheduled tasks use `list` method:

[source,js]
----
var result = cronLib.list();
----

*Parameters*

The list function optionally takes a parameter object with a name filter:

* `options` (_object_) Parameters to list tasks.
** `*pattern*` (_string_) Regular expression the task name must match in full. Leave it empty to
list every task.

*Result*

* `result` (_object_)
** `*jobs*` (_object[]_) Task mapper objects, described above, in the order they were scheduled.

== Examples

=== `Schedule`
[source,js]
----
var cron = require('/lib/cron');

cron.schedule({
    name: 'myTask',
    cron: '0 * * * *',<1>
    times: 5,<2>
    callback: function() {
        log.info('Task is called');
    },
    context: {
        repository: 'my-repo',
        branch: 'master',
        principals: ['role:system.admin'],<3>
        user: {
            login: 'su',
            idProvider: 'system'
        }
    }
});
----
<1> Callback will be run every hour.
<2> Callback will be run 5 times.
<3> System admin role will be used for task run.

[source,js]
----
var cron = require('/lib/cron');

cron.schedule({
    name: 'myTask',
    delay: 1000,<1>
    fixedDelay: 5000,<2>
    times: 5,<3>
    callback: function() {
        log.info('Task is called');
    }
});
----
<1> First callback will be run after 1000ms initial delay.
<2> Next callbacks will be run every 5000ms.
<3> Callbacks will be run 5 times in total.

`reschedule` method is using the same list of parameters.


=== `Unschedule`
[source,js]
----
var cron = require('/lib/cron');

cron.unschedule({
    name: 'myTask' <1>
    });
----
<1> Name of the previously scheduled task. Useful for interruption of tasks without set `times` param.

=== `Get`

[source,js]
----
var cron = require('/lib/cron');

var task = cron.get({
    name: 'myTask'
    });

task == { "name": "myTask",
          "cron": "0 * * * *",
          "cronDescription": "every hour",
          "applicationKey": "com.enonic.app.features",
          "context": {
            "branch": "master",
            "repository": "my-repo",
            "authInfo": {
              "user": {
                "type": "user",
                "key": "user:system:su",
                "displayName": "Super User",
                "disabled": false,
                "login": "su",
                "idProvider": "system"
              },
              "principals": [
                "role:system.admin",
                "role:system.authenticated",
                "role:system.everyone",
                "user:system:su"
              ]
            }
          }
        }
----
