= Cron library

image::https://img.shields.io/badge/xp-6.15.7+-blue.svg[role="right"]

To start using this library, add the following into your `build.gradle` file:

[source,groovy]
----
dependencies {
  include 'com.enonic.lib:lib-cron:{version}'
}
----

== Usage

To use this library in your JavaScript code, it first needs to be required:

[source,js]
----
var cronLib = require('/lib/cron');
----

=== `Schedule`

Next code should be executed to schedule a task:

[source,js]
----
var view = cronLib.schedule(params);
----

`params` description:

[cols="3", options="header"]
|===
|Param name
|Type
|Description

|name
|string
|Unique task name.

|cron
|string
|Cron-pattern (see https://en.wikipedia.org/wiki/Cron[UINX cron pattern])

|times
|number
|Number of task runs. Leave it empty for infinite calls.

|callback
|Function
|Code of task which should be called.

|context
|Context
|Context of the task run.

|===

Where `Context` is:

[cols="1,1,3", options="header"]
|===
|Param name
|Type
|Description

|repository
|string
|Repository id.

 |branch
 |string
 |Branch name.

  |principals
  |string[]
  |Principal keys of groups or roles.

  |attributes
  |Object
  |Map of context attributes.

 |user
 |Object
 |User credentials.

|user.login
|string
|User name.

|user.userStore
|string
|Name of userStore.

|===

=== `Unschedule`

For unscheduling of run task use `unschedule` method:

[source,js]
----
var view = cronLib.unschedule(params);
----
[cols="1,1,3", options="header"]
|===
|Param name
|Type
|Description

|name
|string
|Name of a scheduled task.

|===

=== `Reschedule`
Rescheduling will stop run task by the name and rerun it with set params, which are equal to `schedule` method params:


[source,js]
----
var view = cronLib.reschedule(params);
----

=== `Fetch`

To get particular task use `get` method:

[source,js]
----
var task = cronLib.get(params);
----

Where `params` is:

[cols="1,1,3", options="header"]
|===
|Param name
|Type
|Description

|name
|string
|Name of a scheduled task.

|===

And the result is task mapper object, which contains description of run task:

[cols="1,1,3", options="header"]
|===
|Param name
|Type
|Description

|name
|string
|Name of a scheduled task.

|cron
|string
|Human readable description of UINX cron pattern.

|applicationKey
|string
|Key of application has run the task.

|context
|Object
|Contains information about task context(repo, branch, authInfo).
|===

For fetching a list of current run tasks use `list` method:

[source,js]
----
var taskArray = cronLib.list();
----

Result is an array of task mapper objects, described above.

== Examples

=== `Schedule`
[source,js]
----
var cron = require('/lib/cron');

cron.schedule({
    name: 'myTask',
    cron: '0 * * * *',<1>
    times: 5,<2>
    callback: {
        alert('Task is called');
    },
    context: {
        repository: 'my-repo',
        branch: 'master',
        principals: ['role:system.admin'],<3>
        user: {
            login: 'su',
            userStore: 'system'
        }
    }
});
----
<1> Callback will be run every hour.
<2> Callback will be run 5 times.
<3> System admin role will be used for task run.

`reschedule` method is using the same list of parameters.


=== `Unschedule`
[source,js]
----
var cron = require('/lib/cron');

cron.unschedule({
    name: 'myTask' <1>
    });
----
<1> Name of the previously scheduled task. Useful for interruption of tasks without set `times` param.

=== `Get`

[source,js]
----
var cron = require('/lib/cron');

var task = cron.get({
    name: 'myTask'
    });
---
[source,js]
task == { "name": "myTask",
          "cron": "every hour",
          "applicationKey": "com.enonic.app.features",
          "context": {
            "branch": "master",
            "repository": "my-repo",
            "authInfo": {
              "user": {
                "type": "user",
                "key": "user:system:su",
                "displayName": "Super User",
                "disabled": false,
                "login": "su",
                "idProvider": "system"
              },
              "principals": [
                "role:system.admin",
                "role:system.authenticated",
                "role:system.everyone",
                "user:system:su"
              ]
            }
          }
        }
----
